console.log("HELLO WORLD!");
/* PROJECT STANDARDS:
1. LOGGING STANDARDS:
1.1. MORGAN PACKAGE ORQALI TERMINALDA QAYSI METHODNI ISHLATAYOTGANIMIZ,
QAYSI URL NI ISHLATAYOTGANIMIZ VA ETC LARNI LOG QILYAPMIZ.
1.2. BIZ RESTAURANT CONTROLLER MODULE LIDAGI PAGE LARNI HAM TERMINALDA LOG QILIB OLYAPMIZ.
 SHULAR LOGGING STANDARDSGA MISOL BO`LAOLADI;
 2. NAMING STANDARDS:
 2.1. MISOL RESTAURANT CONTROLLER MODULE LIDA GOHOME METHODINI NOMLAB OLISHIMIZ 
 CAMEL CASE STANDARTI ORQALI AMALGA OSHIRILDI;
 BIZNING STANDARTLARIMIZ BO`YICHA, FUNCTION, METHOD, VARIABLE LARNI NOMLARINI 
 CAMAL CASE ORQALI NOMLAB BORAMIZ;
 2.2. CLASS LARNI ESA BIZ PASCAL CASE STANDARTI BILAN NOMLAB BORAMIZ
 2.3. FOLDERLARNI NOMLASHDA KEBAB CASE STANDARTIDAN FOYDALANAMIZ;
 2.4. CSS NI ICHIDA ESA BIZ SNAKE CASE STANDARTIDAN FOYDALANAMIZ;
3. ERROR HANDLING:
*/

// RESPONSE LAR NECHA XIL BO`LADI:
// 1. SEND KO`RINISHIDA BO`LADI
// 2. JSON
// 3. REDIRECT YA`NI BIRON BOSHQA URL GA YO`NALTIRILGAN BO`LADI`
// 4. END BO`LISHI MUMKIN
// 5. RENDER HAM BO`LISHI MUMKIN`

// API = APPLICATION PROGRAMMING LANGUAGE DEGANI
// API LAR SERVER VA CLIENT ORASINI BOG`LAB BERUVCHI PROTOCOL,
// PACKAGE, FUNCTION, METHODLARDAN
// FOYDALANADI.
// APILAR NI HAM TURLARI BOR:
// ENG MASHHUR TURLARI:
// 1. TRADITIONAL API, ODATDA ODDIYGINA API HAM DEB NOMLANADI,
// 2. REST API
// 3. GRAPHQL API

/*
 * Request:
 * Traditional Api
 * Rest Api
 * GraphQL Api
 * ...
 */

/* Frontend Development:
 * Traditional FD => SSR => EJS
 * Modern FD => SPA => REACT
 */

/* Cookies:
 * request join
 * self destroy
 */

/* Validation:
 * Frontend validation
 * Backend validation
 * Database validation
 */

/*
 * PM2 COMMANDS:
 * pm2 ls
 * pm2 start dist/server.js --name=UZBEGIM
 * pm2 start "npm run start:prod" --name=UZBEGIM
 * pm2 start "yarn run start:prod" --name=UZBEGIM
 * pm2 stop id
 * pm2 delete id
 * pm2 restart id
 * pm2 monit
 * pm2 kill (pm2 da run bo`lgan barcha loyihalarni o`chirib yuboradi)
 */
